service:
  name: reddit-nsfw-webhook-filter

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  info:
    handler: handler.noGet
    events:
      - http:
          method: get
          path: /
  webhook:
    handler: handler.forwardWebhook
    events:
      - http:
          method: post
          path: /
      - http:
          method: post
          path: webhook
